"""Build (and optionally execute) the analysis notebook.

The notebook is generated rather than hand-maintained so it cannot drift from
the source modules: every cell calls the same functions the scripts do. It
walks through loading records, inspecting a single example's signals,
comparing estimators, and reproducing the calibration and application results.

Usage::

    python scripts/build_notebook.py            # build and execute
    python scripts/build_notebook.py --no-exec  # build only
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import nbformat  # noqa: E402
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook  # noqa: E402

from src.config import NOTEBOOK_DIR, PROJECT_ROOT, ensure_output_dirs  # noqa: E402
from src.logging_utils import configure_logging  # noqa: E402

logger = logging.getLogger("build_notebook")

#: Filename of the generated notebook.
NOTEBOOK_NAME: str = "uncertainty_analysis.ipynb"

#: Seconds allowed per cell during execution.
_CELL_TIMEOUT: int = 300


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments.

    Returns:
        The parsed arguments.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--no-exec",
        action="store_true",
        help="Build the notebook without executing it.",
    )
    parser.add_argument("--output-dir", type=Path, default=NOTEBOOK_DIR)
    return parser.parse_args()


def build_cells() -> list:
    """Construct the notebook's cells.

    Returns:
        A list of nbformat cells.
    """
    return [
        new_markdown_cell(
            "# Uncertainty Quantification in Language Models\n"
            "\n"
            "**Track 2 — analysis notebook**\n"
            "\n"
            "This notebook is generated by `scripts/build_notebook.py` and calls "
            "the same functions the command-line scripts do, so it cannot drift "
            "from the source modules.\n"
            "\n"
            "Run `scripts/run_experiment.py` first to produce the records this "
            "reads."
        ),
        new_code_cell(
            "import sys\n"
            "from pathlib import Path\n"
            "\n"
            "sys.path.insert(0, str(Path.cwd().parent))\n"
            "\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "from IPython.display import Image, display\n"
            "\n"
            "from src.analysis import analyse_task, top_signals\n"
            "from src.config import FIGURES_DIR, TASKS\n"
            "from src.experiment import records_for_task, signal_columns\n"
            "from src.signals import SIGNAL_REGISTRY, get_spec\n"
            "\n"
            "pd.set_option('display.width', 120)\n"
            "pd.set_option('display.max_columns', 20)"
        ),
        new_markdown_cell(
            "## 1. What a single example looks like\n"
            "\n"
            "Each record carries the greedy generation, the sampled "
            "generations, every uncertainty signal, and the wall-clock cost of "
            "each generation pass."
        ),
        new_code_cell(
            "records = records_for_task('gsm8k')\n"
            "example = records[0]\n"
            "\n"
            "print('Question:', example['question'][:200])\n"
            "print()\n"
            "print('Greedy answer:', example['greedy_canonical'], '| correct:', example['greedy_correct'])\n"
            "print('Majority answer:', example['majority_answer'], '| correct:', example['majority_correct'])\n"
            "print()\n"
            "print('Distinct sampled answers:', sorted(set(example['sample_canonical'])))\n"
            "print()\n"
            "print('Timings (s):', {k: round(v, 2) for k, v in example['timings'].items()})"
        ),
        new_code_cell(
            "signal_view = pd.DataFrame(\n"
            "    [\n"
            "        {\n"
            "            'signal': name,\n"
            "            'value': example['signals'][name],\n"
            "            'granularity': get_spec(name).granularity,\n"
            "            'cost': get_spec(name).cost_tier,\n"
            "        }\n"
            "        for name in example['signals']\n"
            "    ]\n"
            ")\n"
            "signal_view.sort_values(['granularity', 'signal']).reset_index(drop=True)"
        ),
        new_markdown_cell(
            "## 2. Do the signals separate right from wrong answers?\n"
            "\n"
            "The mechanism every downstream metric depends on: a useful signal "
            "must take systematically different values on correct and incorrect "
            "answers."
        ),
        new_code_cell(
            "rows = []\n"
            "for task in TASKS:\n"
            "    task_records = records_for_task(task)\n"
            "    columns = signal_columns(task_records)\n"
            "    correct = np.array([r['greedy_correct'] for r in task_records])\n"
            "    for name in ['mean_entropy', 'log_perplexity', 'semantic_entropy', 'self_consistency']:\n"
            "        values = columns[name]\n"
            "        finite = np.isfinite(values)\n"
            "        rows.append({\n"
            "            'task': task,\n"
            "            'signal': name,\n"
            "            'mean_when_correct': np.nanmean(values[finite & correct]),\n"
            "            'mean_when_wrong': np.nanmean(values[finite & ~correct]),\n"
            "        })\n"
            "\n"
            "separation = pd.DataFrame(rows)\n"
            "separation['gap'] = separation['mean_when_wrong'] - separation['mean_when_correct']\n"
            "separation"
        ),
        new_markdown_cell(
            "## 3. Ranked estimator comparison\n"
            "\n"
            "AUROC treats an incorrect answer as the positive class and the "
            "uncertainty score as the ranker. Bootstrap intervals are the point "
            "of this table: where they overlap, the ordering is not resolved."
        ),
        new_code_cell(
            "analyses = {task: analyse_task(task) for task in TASKS}\n"
            "\n"
            "for task, analysis in analyses.items():\n"
            "    print(f'=== {task} | greedy accuracy {analysis.greedy_accuracy:.3f} '\n"
            "          f'| {analysis.num_test} held-out examples ===')\n"
            "    table = pd.DataFrame([\n"
            "        {\n"
            "            'signal': ev.display_name,\n"
            "            'cost': ev.cost_tier,\n"
            "            'AUROC': round(ev.auroc.value, 3),\n"
            "            'CI low': round(ev.auroc.lower, 3),\n"
            "            'CI high': round(ev.auroc.upper, 3),\n"
            "            'AURC': round(ev.aurc.value, 3),\n"
            "            'ECE': round(ev.ece_equal_mass, 3),\n"
            "        }\n"
            "        for ev in analysis.evaluations[:10]\n"
            "    ])\n"
            "    display(table)\n"
            "    print()"
        ),
        new_markdown_cell(
            "## 4. Does semantic clustering beat plain string matching?\n"
            "\n"
            "The targeted ablation. Semantic entropy and lexical entropy differ "
            "*only* in whether answers are grouped by meaning or by exact "
            "string, so the gap between them is what NLI clustering buys."
        ),
        new_code_cell(
            "comparison = []\n"
            "for task, analysis in analyses.items():\n"
            "    by_name = {ev.signal: ev for ev in analysis.evaluations}\n"
            "    for name in ['semantic_entropy', 'weighted_semantic_entropy', 'lexical_entropy']:\n"
            "        if name in by_name:\n"
            "            comparison.append({\n"
            "                'task': task,\n"
            "                'method': by_name[name].display_name,\n"
            "                'AUROC': round(by_name[name].auroc.value, 3),\n"
            "            })\n"
            "\n"
            "pd.DataFrame(comparison).pivot(index='method', columns='task', values='AUROC')"
        ),
        new_markdown_cell(
            "## 5. Calibration\n"
            "\n"
            "A raw entropy is not a probability, so each signal is mapped to "
            "P(correct) by a logistic calibrator **fitted on the dev split** and "
            "evaluated on the held-out split. Fitting on the reported split "
            "would make every method look far better calibrated than it is."
        ),
        new_code_cell(
            "for task in TASKS:\n"
            "    for strategy in ('fixed_width', 'equal_mass'):\n"
            "        path = FIGURES_DIR / f'reliability_{strategy}_{task}.png'\n"
            "        if path.exists():\n"
            "            display(Image(filename=str(path)))"
        ),
        new_markdown_cell(
            "## 6. Applications\n"
            "\n"
            "### Selective answering, confidence tags, and the cascade"
        ),
        new_code_cell(
            "for task, analysis in analyses.items():\n"
            "    print(f'=== {task} | gating on {get_spec(analysis.best_signal).display_name} ===')\n"
            "    display(pd.DataFrame([p.as_dict() for p in analysis.selective])[\n"
            "        ['target_accuracy', 'test_coverage', 'test_accuracy', 'target_met_on_test']\n"
            "    ])\n"
            "    display(pd.DataFrame([t.as_dict() for t in analysis.tiers]))\n"
            "    print()"
        ),
        new_code_cell(
            "cascade = analyses['gsm8k'].cascade\n"
            "if cascade is not None:\n"
            "    print(f'Greedy only:              {cascade.greedy_accuracy:.3f}  (1.00 generations)')\n"
            "    print(f'Self-consistency always:  {cascade.self_consistency_accuracy:.3f}  '\n"
            "          f'({1 + cascade.num_samples:.2f} generations)')\n"
            "    if cascade.selected:\n"
            "        s = cascade.selected\n"
            "        print(f'Uncertainty-gated:        {s.test_accuracy:.3f}  '\n"
            "              f'({s.mean_generations:.2f} generations, '\n"
            "              f'{s.test_escalation_rate:.0%} escalated)')\n"
            "    display(pd.DataFrame([p.as_dict() for p in cascade.curve]))"
        ),
        new_markdown_cell("## 7. All figures"),
        new_code_cell(
            "for path in sorted(FIGURES_DIR.glob('*.png')):\n"
            "    print(path.name)\n"
            "    display(Image(filename=str(path)))"
        ),
    ]


def main() -> int:
    """Build and optionally execute the notebook.

    Returns:
        Process exit code.
    """
    args = parse_args()
    configure_logging()
    ensure_output_dirs()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    notebook = new_notebook(cells=build_cells())
    notebook.metadata.kernelspec = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }

    path = args.output_dir / NOTEBOOK_NAME
    nbformat.write(notebook, path)
    logger.info("Wrote %s (%d cells)", path, len(notebook.cells))

    if args.no_exec:
        return 0

    from nbclient import NotebookClient

    logger.info("Executing notebook (this reads results/ and figures/)")
    client = NotebookClient(
        notebook,
        timeout=_CELL_TIMEOUT,
        kernel_name="python3",
        resources={"metadata": {"path": str(args.output_dir)}},
    )
    client.execute()
    nbformat.write(notebook, path)
    logger.info("Executed and saved %s", path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
